### ISSUE TITLE
Some users can't save cookie state.

### ISSUE THREAD

**Issue by codecypherz** [codecypherz/ffxivfisher#29]
Needs more investigation.  Might just be browser/client settings preventing the data from being saved or cleared occasionally.

**Comment by kchoppin** [comment]
I'm having the same issue in the latest version of firefox. Looking at the cookies, they do not have an expiry set, so they're being set as session cookies and are being deleted when the session ends. I can get them to stay when I give them an expiry date.

**Comment by codecypherz** [comment]
Okay this is now fixed in production.  Setting the Number.MAX_VALUE was somehow still ending up as a session cookie.  Setting an explicit value that was less than that but still arbitrarily large ultimately fixed the issue.  I also added code to migrate existing session cookies to be persistent, so no data should be lost for anyone.
